# disabled features
TAP_DANCE_ENABLE = no
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
EXTRAKEY_ENABLE = no
SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no
MAGIC_ENABLE = no
LEADER_ENABLE = no
REPEAT_KEY_ENABLE = no

# enabled features
LTO_ENABLE = yes
COMBO_ENABLE = yes
CAPS_WORD_ENABLE = yes
RELEASE_GATE_ENABLE = yes
